version: '3'

services:
  #php service
  app:
    build: docker/php
    image: php:7.4-fpm
    volumes:
      - ./:/app
    depends_on:
      - db
  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT}:3306
    volumes:
      #backup of db
      - dbdata:/var/lib/mysql
    environment:
      # the entrypoint script would fail to work if you set MYSQL_USER to root;
      # specifically line will fail to create the second user 'root'@'%' since it will already exist in the users table
      # from above. If you want to use root as your user, you only need to set MYSQL_ROOT_PASSWORD.
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db
    environment:
      PMA_HOST: db

volumes:
  dbdata:
    driver: local